<?php

//$name1 = ["Bar", "Gew", "Ger", "Dan", "Cle"];
//$name2 = ["grod", "gard", "follas", "den"];
//$surname1 = ["Wilder", "Grase", "Trow", "Brean"];
//$surname2 = ["dold", "gard", "fols", "dren"];
//$superName = $name1[rand(0, count($name1) - 1)] . $name2[rand(0, count($name2) - 1)] . " " . $surname1[rand(0, count($surname1) - 1)] . $surname2[rand(0, count($surname2) - 1)];
//echo $superName;
//echo "</br>";
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!--<script src="init.js"></script>-->
    <link rel="stylesheet" href="/JSclicker/styles/styles.css">
    <script src="/JSclicker/code/data.js"></script>
</head>
<body>
<div style="text-align: center" id="selectHeroClass">
    <h1 style="text-align: center">Select your class</h1>
    <button style="text-align: center;" id="class-warrior" class="button-x button4  " onclick="selectClass(this.id); ">Warrior</button>
    <button style="text-align: center;" id="class-rogue" class="button-x button4  " onclick="selectClass(this.id); ">Rogue</button>
    <button style="text-align: center;" id="class-mage" class="button-x button4  " onclick="selectClass(this.id); ">Mage</button>
</div>
<div id="gameArea" style="visibility: hidden">
<div id="stats" class="border div-inline" style="width: 25%">
    <h1 id="name" ></h1>
    <h1 id="className"></h1>
    <h2 id="lvl"></h2>
    <h2 id="exp"></h2>
    <h2 id="strength"></h2>
    <h2 id="agility"></h2>
    <h2 id="stamina"></h2>
    <h2 id="stealth"></h2>
    <h2 id="weapon"></h2>
    <h4 id="weaponView"></h4>
    <h2 id="attackPower"></h2>
    <h2 id="health"></h2>
    <div id="inventory" style="background-color: #7a6b45">
    </div>
</div>
<div id="area" class="border hidden div-inline area">
    <div style="display: inline-block">
        <h2 id="nameEnemy"></h2>
        <h1 id="faceEnemy"></h1>
    </div>
    <hr>
    <div id="info"></div>
    <h4 id="healthEnemy"></h4>
    <h4 id="damageEnemy"></h4>
    <h4></h4>
    <button id="hit" class="button-x button3" onclick="personHit()">Hit</button>
    <button id="runaway" class="button-x button3" onclick="runaway()">Runaway</button>
</div>
<div id="stat-button-area" class="hidden" >

<button onclick="getGun(this.id)" class="button-x" id="sword">getGunSword</button>
<button onclick="getGun(this.id)" class="button-x" id="axe">getGunAxe</button>
<button onclick="getGun(this.id)" class="button-x" id="dagger">getGunDagger</button>
<button onclick="getGun(this.id)" class="button-x" id="catana">getGunCatana</button>
</br>
<button onclick="riseStat(this.id)" class="button-x" id="strength-Stat">strengthStat+</button>
<button onclick="riseStat(this.id)" class="button-x" id="agility-Stat">agilityStat+</button>
<button onclick="riseStat(this.id)" class="button-x" id="stamina-Stat">staminaStat+</button>
<button onclick="riseStat(this.id)" class="button-x" id="stealth-Stat">stealthStat+</button>
</div>
<button style="text-align: center;" id="fight" class="button-x button3" onclick="newFight()">FIGHT</button>
<button style="text-align: center;" id="goToPlace" class="button-x button4 placeChange" onclick="showPlaces()">GO TO PLACE</button>
<div id="places" class="hidden">
<button style="text-align: center;" id="goToPlace-village" class="button-x button4 placeChange " onclick="showPlaces(); goToPlace(this.id)">Village</button>
<button style="text-align: center;" id="goToPlace-town" class="button-x button4 placeChange " onclick=" showPlaces();goToPlace(this.id)">Small Town</button>
<button style="text-align: center;" id="goToPlace-castle" class="button-x button4 placeChange " onclick="showPlaces();goToPlace(this.id)">Castle</button>
<button style="text-align: center;" id="goToPlace-forest" class="button-x button4 placeChange " onclick="showPlaces(); goToPlace(this.id)">Forest</button>
</div>
</div>
<script data-main="scripts/main" src="scripts/require.js"></script>
<!--<script src="/JSclicker/code/data.js"></script>-->
<!--<script src="/JSclicker/code/actions.js"></script>-->
<!--<script src="/JSclicker/init.js"></script>-->
<!--<script src="/JSclicker/code/fight.js"></script>-->
</body>
</html>