<?php

$name1 = ["Bar", "Gew", "Ger", "Dan", "Cle"];
$name2 = ["grod", "gard", "follas", "den"];
$surname1 = ["Wilder", "Grase", "Trow", "Brean"];
$surname2 = ["dold", "gard", "fols", "dren"];
$superName = $name1[rand(0, count($name1) - 1)] . $name2[rand(0, count($name2) - 1)] . " " . $surname1[rand(0, count($surname1) - 1)] . $surname2[rand(0, count($surname2) - 1)];
echo $superName;
echo "</br>";
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!--<script src="init.js"></script>-->
    <link rel="stylesheet" href="/JSclicker/styles/styles.css">
    <script src="/JSclicker/code/data.js"></script>
</head>
<body>


<div id="stats" class="border div-inline" style="width: 25%">
    <h1 id="name"></h1>
    <h2 id="lvl"></h2>
    <h2 id="exp"></h2>
    <h2 id="strength"></h2>
    <h2 id="agility"></h2>
    <h2 id="stamina"></h2>
    <h2 id="stealth"></h2>
    <h2 id="weapon"></h2>
    <h4 id="weaponView"></h4>
    <h2 id="attackPower"></h2>
    <h2 id="health"></h2>
</div>
<div id="area" class="border hidden div-inline area">
    <div style="display: inline-block">
        <h2 id="nameEnemy"></h2>
        <h1 id="faceEnemy"></h1>
    </div>
    <hr>
    <div id="info"></div>
    <h4 id="healthEnemy"></h4>
    <h4 id="damageEnemy"></h4>
    <h4></h4>
    <button id="hit" class="button-x button3" onclick="personHit()">Hit</button>
    <button id="runaway" class="button-x button3" onclick="runaway()">Runaway</button>
</div>
<div id="stat-button-area" class="hidden" >
<!---->
<!--<button onclick="getGun(this.id)" class="button-x" id="sword">getGunSword</button>-->
<!--<button onclick="getGun(this.id)" class="button-x" id="axe">getGunAxe</button>-->
<!--<button onclick="getGun(this.id)" class="button-x" id="dagger">getGunDagger</button>-->
<!--<button onclick="getGun(this.id)" class="button-x" id="catana">getGunCatana</button>-->
</br>
<button onclick="riseStat(this.id)" class="button-x" id="strength-Stat">strengthStat+</button>
<button onclick="riseStat(this.id)" class="button-x" id="agility-Stat">agilityStat+</button>
<button onclick="riseStat(this.id)" class="button-x" id="stamina-Stat">staminaStat+</button>
<button onclick="riseStat(this.id)" class="button-x" id="stealth-Stat">stealthStat+</button>
</div>
<button style="text-align: center;" id="fight" class="button-x button3" onclick="newFight()">FIGHT</button>
<div style="background-color: #4d4d4d; width: 100%; height: 20px;"></div>

<script src="/JSclicker/code/data.js"></script>
<script src="/JSclicker/init.js"></script>
<script src="/JSclicker/code/fight.js"></script>
</body>
</html>